apiVersion: v1
data:
  secretkey: aDdsYjhlWTJaZXZ4QzlaMGZVOW85V3czbGIrNnVKbGRaeTVvYVRjcFBYUE1vSjhmZzVtMmxLLzhjekNYZVY5cAp6a3AxZzlSQ0hja3FtNVMvU01jMzNXdHA0OEdDV1lGUTVJSUlmejY3bWNRU0cxNnN4VjVSVDZYZkppYm9VZmYzClUyWlZJcWc5NzQ1YllmTjRBaW5iMUNFRmVLSWk1eU5ZNCt0UFdXOTN6cms9
kind: Secret
metadata:
  creationTimestamp: null
  name: sample-secret
